import { DEMO_TODAY } from "@/config/app";

import { subscriptionSchema, type Subscription } from "./schema";

export const demoSubscriptions: Subscription[] = subscriptionSchema
  .array()
  .parse([
    {
      id: "sub_northstar",
      merchantName: "NORTHSTAR CINEMA 4821",
      displayName: "Northstar Cinema",
      category: "Video streaming",
      amountMinor: 1899,
      currency: "USD",
      frequency: "monthly",
      nextBillingDate: "2026-09-21",
      startDate: "2024-04-21",
      status: "active",
      paymentMethodNickname: "Everyday card •• 42",
      website: "https://example.com",
      source: "statement_import",
      previousAmountMinor: 1599,
      savingsCandidate: false,
      brandColor: "#176b57",
    },
    {
      id: "sub_cloudnest",
      merchantName: "CLOUDNEST STORAGE",
      displayName: "CloudNest 200 GB",
      category: "Cloud storage",
      amountMinor: 299,
      currency: "USD",
      frequency: "monthly",
      nextBillingDate: "2026-09-24",
      startDate: "2023-11-24",
      status: "active",
      paymentMethodNickname: "Everyday card •• 42",
      website: "https://example.com",
      source: "manual",
      savingsCandidate: false,
      brandColor: "#397a9a",
    },
    {
      id: "sub_tempo",
      merchantName: "TEMPO MUSIC",
      displayName: "Tempo Music",
      category: "Music",
      amountMinor: 1099,
      currency: "USD",
      frequency: "monthly",
      nextBillingDate: "2026-09-26",
      startDate: "2025-01-26",
      status: "active",
      paymentMethodNickname: "Travel card •• 18",
      website: "https://example.com",
      source: "statement_import",
      savingsCandidate: false,
      brandColor: "#7657a8",
    },
    {
      id: "sub_dailybrief",
      merchantName: "DAILY BRIEF DIGITAL",
      displayName: "The Daily Brief",
      category: "News and publications",
      amountMinor: 800,
      currency: "USD",
      frequency: "monthly",
      nextBillingDate: "2026-10-01",
      startDate: "2024-08-01",
      status: "active",
      paymentMethodNickname: "Everyday card •• 42",
      website: "https://example.com",
      source: "statement_import",
      savingsCandidate: true,
      brandColor: "#bd613f",
    },
    {
      id: "sub_formflow",
      merchantName: "FORM AND FLOW",
      displayName: "Form & Flow",
      category: "Fitness",
      amountMinor: 8999,
      currency: "USD",
      frequency: "annual",
      nextBillingDate: "2026-10-05",
      startDate: "2026-09-05",
      trialEndDate: "2026-09-23",
      status: "trial",
      paymentMethodNickname: "Travel card •• 18",
      website: "https://example.com",
      source: "manual",
      savingsCandidate: false,
      brandColor: "#df9a2f",
    },
    {
      id: "sub_viewbox",
      merchantName: "VIEWBOX PLUS",
      displayName: "ViewBox Plus",
      category: "Video streaming",
      amountMinor: 1299,
      currency: "USD",
      frequency: "monthly",
      nextBillingDate: "2026-10-08",
      startDate: "2025-12-08",
      status: "active",
      paymentMethodNickname: "Everyday card •• 42",
      website: "https://example.com",
      source: "manual",
      savingsCandidate: true,
      brandColor: "#bf4f5f",
    },
    {
      id: "sub_focusforge",
      merchantName: "FOCUSFORGE APP",
      displayName: "FocusForge",
      category: "Software",
      amountMinor: 600,
      currency: "USD",
      frequency: "every_two_months",
      nextBillingDate: "2026-10-12",
      startDate: "2025-06-12",
      status: "paused",
      paymentMethodNickname: "Travel card •• 18",
      website: "https://example.com",
      source: "manual",
      savingsCandidate: false,
      brandColor: "#596273",
    },
  ]);

export const demoBudgetMinor = 8500;
export const demoSavingsGoalMinor = 2500;
export const demoSpentThisMonthMinor = 4097;
export const demoToday = DEMO_TODAY;
